config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root 'visitors#index'

  resources :employees, only: [:edit, :update, :index, :new, :create, :destroy]
  #TO DO: Resolver o redirecionamento da rota DESTROY
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :user
  
  as_enum :department, [:accounting, :finance, :customer_service, :budgeting, :it],  prefix: true, map: :string

  def translated_department
    return if department.blank?

    I18n.t("activerecord.attributes.employee.department.#{department}")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :employees
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:edit, :update]

  def index
    @employees = Employee.all.order(created_at: :desc)
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employees_params)
    @employee.user = current_user

    if @employee.save
      redirect_to(employees_path, notice: 'Criado com sucesso')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @employee.update(employees_params)
      redirect_to(employees_path, notice: 'Cadastro atualizado com sucesso.')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @employee = Employee.find(params[:id])

    if @employee.destroy
      redirect_to(employees_path, notice: 'Excluído com sucesso')
    else
      redirect_to(employees_path, notice: 'Não foi possível excluir')
    end
  end

  private 

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employees_params
    params.require(:employee)
          .permit(:name, :department, :email)
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  skip_before_action :authenticate_user!

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def departments
    [
      { it: 'áyslan' },
    ]
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/edit.html.erb
<%= form_with(model: @employee, local: true) do |form| %>
  <div class="row mb-3" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= form.label :name, "Nome", class: "form-label" %>
      <%= form.text_field :name, class: "form-control", placeholder: "Digite o Nome" %>
    </div>
  </div>

  <div class="row mb-3" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= form.label :department, "Setor", class: "form-label" %>
      <%= form.select :department, Employee.departments.keys.map { |key| [I18n.t("activerecord.attributes.employee.department.#{key}"), key] }, {}, { class: 'form-control', include_blank: true } %>
    </div>
  </div>

  <div class="row mb-3" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= form.label :email, "E-mail", class: "form-label" %>
      <%= form.text_field :email, class: "form-control", placeholder: "Digite o E-mail" %>
    </div>
  </div>

  <div class="row mb-4" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= link_to 'Voltar', employees_path, class: 'btn btn-secondary ms-2' %>
      <%= button_tag "Criar", class: 'btn btn-blue' %>
    </div>
  </div>
<% end %>

app/views/employees/index.html.erb
<h2 class="float-start mt-4" style="margin-right: 10px;">Maceió IN</h2>

<div class="float-end mt-4 me-3">
  <%= link_to(new_employee_path, class: 'btn btn-blue') do %>
    <i class="bi bi-plus-lg"></i> Criar um novo cadastro
  <% end %>
</div>

<table class="table table-striped table-hover table-bordered">
  <thead>
    <tr>
      <th class="table-header">Nome</th>
      <th class="table-header">Setor</th>
      <th class="table-header">E-mail</th>
      <th class="table-header">Criado por</th>
      <th class="table-header"></th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.translated_department %></td>
        <td><%= employee.email %></td>
        <td><%= employee.user.email %></td>
        <td class="d-inline-flex w-100">
          <%= link_to('Editar', edit_employee_path(employee), class: 'btn btn-sm btn-orange') %>
          <%= button_to 'Excluir', employee_path(employee), class: 'btn btn-sm btn-red', method: :delete, data: { turbo_confirm: "Tem certeza?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/employees/new.html.erb
<%= form_with(model: @employee, local: true) do |form| %>
  <div class="row mb-3" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= form.label :name, "Nome", class: "form-label" %>
      <%= form.text_field :name, class: "form-control", placeholder: "Digite o Nome" %>
    </div>
  </div>

  <div class="row mb-3" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= form.label :department, "Setor", class: "form-label" %>
      <%= form.select :department, Employee.departments.keys.map { |key| [I18n.t("activerecord.attributes.employee.department.#{key}"), key] }, {}, { class: 'form-control', include_blank: true } %>
    </div>
  </div>

  <div class="row mb-3" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= form.label :email, "E-mail", class: "form-label" %>
      <%= form.text_field :email, class: "form-control", placeholder: "Digite o E-mail" %>
    </div>
  </div>

  <div class="row mb-4" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= link_to 'Voltar', employees_path, class: 'btn btn-secondary ms-2' %>
      <%= button_tag "Criar", class: 'btn btn-blue' %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Maceio IN</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="//code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="//code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="//stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
  </head>

  <body>
    <header>
      <div class="logo d-inline-flex">
        <img
          src="https://maceioalgovbr.dhost.cloud/assets/images/logo_prefeitura_de_maceio.svg"
          alt="login form"
          class="img-fluid"
        />
      </div>
    </header>
    <nav class="navbar navbar-expand-lg menu">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to('Início', root_path, class: 'nav-link') %>
          </li>
          <% if current_user.present? %>
            <li class="nav-item">
              <%= link_to('Funcionários', employees_path, class: 'nav-link') %>
            </li>
          <% end %>
          <li class="nav-item">
            <% if current_user.present? %>
              <%= button_to "Sair", destroy_user_session_path, class: 'nav-link', method: :delete, data: { turbo: false  } %>
            <% else %>
              <%= link_to('Login', new_user_session_path, class: 'nav-link') %>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/visitors/index.html.erb
<header class="text-center">
  <h1 class="topic">Secretária da Fazenda de Maceió (SEFAZ)</h1>
  <p>Aqui você encontra tudo o que precisa saber sobre a SEFAZ.</p>
</header>

<main class="container">
  <section>
    <h2 class="topic">Quem somos?</h2>
    <p>A Secretaria Municipal de Fazenda de Maceió é responsável por planejar e executar políticas fiscais, tributárias, orçamentárias e financeiras do município. Ela arrecada tributos municipais e lida com questões como isenções e revisões, além de organizar o calendário fiscal e orçamentário. A Secretaria também foca no desenvolvimento econômico e na desburocratização fiscal.</p>
  </section>

  <section>
    <h2 class="topic">O que fazemos?</h2>
    <p>Planejamos e executamos as políticas fiscal, tributária, orçamentária e financeira de competência do Município, arrecadamos os tributos municipais e atuamos nas inclusões, imunidades, isenções, arbitramento, revisões e outros casos que requeiram interpretações da legislação. Somos responsáveis por organizar o calendário fiscal e orçamentário do município. Também atuamos no planejamento de políticas públicas e medidas de desburocratização fiscal voltadas ao desenvolvimento econômico.</p>
  </section>

  <section>
    <h2 class="topic">Serviços</h2>
    <ul class="list-group">
      <li class="list-group-item">IPTU 2024</li>
      <li class="list-group-item">Emissão de Nota Fiscal de Serviço</li>
      <li class="list-group-item">Certidões de Registro Fiscal e Autenticidade</li>
      <li class="list-group-item">Guias de Pagamento</li>
      <li class="list-group-item">ITBI e BCI</li>
      <li class="list-group-item">Agendamento</li>
      <li class="list-group-item">Serviços Fazenda</li>
      <li class="list-group-item">Portal do Cidadão</li>
      <li class="list-group-item">Participa Maceió</li>
      <li class="list-group-item">Emissão de Guias</li>
      <li class="list-group-item">Sala do Empreendedor</li>
      <li class="list-group-item">Taxa de Localização</li>
      <li class="list-group-item">Chamados de Atendimento</li>
      <li class="list-group-item">Abertura de Processos Administrativos</li>
      <li class="list-group-item">Contencioso Online</li>
      <li class="list-group-item">Quadro Demonstrativo de Cargos em Comissão - SEFAZ</li>
    </ul>
  </section>
</main>